### PR TITLE
feat: use `@rollup/plugin-typescript` to resolve id

### PR DESCRIPTION
**Pull request by hanayashiki**
I'm trying to use the resolveId function of `@rollup/plugin-typescript` to do the module resolution, replacing the current custom way of doing that. This may have the following benefits:

1. Automatically follows typescript's implementation. If the code shows no error in your intellisense, it should just work. This PR should pass all current test cases (currently having trouble on windows, which I don't have) and past feature requests, and change the previous way of implementing features not satisfying typescript case by case.
2. The main file loader.esm should be shorter, and with less magic code to pass the testcase.

**I really hope there could be a chance to fix that on windows. Help wanted.**

### CODE REVIEW

**Comment by hanayashiki** [comment]
Can someone with a window help me with the failed case on windows? it seems `@rollup/plugin-typescript` cannot resolve with the extension on windows.

```
    Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'D:/a/esbuild-node-loader/esbuild-node-loader/test/fixture.export' imported from D:/a/esbuild-node-loader/esbuild-node-loader/test/fixture.import.ts
```

**Comment by userquin** [comment]
> 
> 
> Can someone with a windows help me with the failed case on windows? it seems `@rollup/plugin-typescript` cannot resolve with the extension on windows.
> 
> ```
>     Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'D:/a/esbuild-node-loader/esbuild-node-loader/test/fixture.export' imported from D:/a/esbuild-node-loader/esbuild-node-loader/test/fixture.import.ts
> ```

Should be relative, that is, you need prefix it with `file:///`, see #6. 

If the problem comes from the ts plugin, should be fixed on the plugin.

Context:
https://github.com/nodejs/node/issues/31710
https://github.com/vitejs/vite/issues/1487

**Comment by hanayashiki** [comment]
> > Can someone with a windows help me with the failed case on windows? it seems `@rollup/plugin-typescript` cannot resolve with the extension on windows.
> > ```
> >     Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'D:/a/esbuild-node-loader/esbuild-node-loader/test/fixture.export' imported from D:/a/esbuild-node-loader/esbuild-node-loader/test/fixture.import.ts
> > ```
> 
> Should be relative, that is, you need prefix it with `file:///`, see #6.
> 
> If the problem comes from the ts plugin, should be fixed on the plugin.
> 
> Context: [nodejs/node#31710](https://github.com/nodejs/node/issues/31710) [vitejs/vite#1487](https://github.com/vitejs/vite/issues/1487)

Thank you. I'm kind of unfamiliar with node's [URL](https://nodejs.org/api/url.html#urlparseurlstring-parsequerystring-slashesdenotehost) module, and have been long away from windows. I'm now using `fileURLToPath` and it works out fine.

When I'm writing the code, I was thinking about what does this library do?

I think it should mainly handle the following cases:

1. Transpiling files ending with ts and tsx (of course)

1. Treating all typescript (which predominantly use esmodule grammar) as module.

1. Bridging the incompatibility between node import specifers  and typescript import specifiers

In typescript, it is okay to `import a from './a'`, as long as there's `a.<ext>` or `a/index.<ext>` that is recognized by typescript's module resolution. However, [typescript does a bad job at transpiling them to runnable ecma modules](https://github.com/microsoft/TypeScript/issues/42151).

However, typescript does provide module resolution apis, which maps a typescript import specifier to a concrete file on the disk. We should leverage that API (or write our own to mimic that, before this PR), to guide node runtime to resolve the file we want, and load them on the fly.

Before this PR, esmo will fail on `import 'react-dom/server'` because node requires us to give the extension (`import 'react-dom/server.js'`, to be correct), even for bare specifiers, in contrast to commonjs. However, `import 'react-dom/server'` is recognized almost by every build tool, and we should bridge that in esmo.

Now, since typescript allows `react-dom/server` in a esmodule format, we use its module resolution algorithm to find `react-dom/server.js`, and pass it to `defaultResolve`, then, voila, we can write the same code and run them using the correct module format.

However, we should also pay attention to the case that node can handle, but typescript can't. For example, import using URL like `file://`. For any paths that can't be handled by typescript, which of course can't be included into any valid typescript with proper type-checking, we can do nothing but passing them to `defaultResolve`.

**Comment by hanayashiki** [comment]
@antfu would you please take a look at this?

**Comment by sandy2008** [comment]
This PR looks helpful.

**Review by sandy2008 — APPROVED** [review]

**Pull request merged**
